# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57d635e6adc5f45cae46a42ca9b521d0d2c194441fd6d1a5290efce9602860ef3c85bd831889ed4ea0b58290b9f20231268d894f38178bddccbedd1c6a4feb3e

test:
  secret_key_base: 838da0a109c26bf09ff0a82e8eeca698c3e191b4f5886ea6d16859c0b34f4ed408b95014e30e359f17bc785e6d0c79fe0971aaefcb815d1013bb0a073876aedc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
